CREATE TABLE IF NOT EXISTS job (
	id INTEGER auto_increment NOT NULL,
	status ENUM('WAITING', 'IN_PROCESS', 'FINISHED', 'ERROR') NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	CONSTRAINT job_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS import_job (
	id INTEGER auto_increment NOT NULL,
	CONSTRAINT import_job_pk PRIMARY KEY (id),
	CONSTRAINT job_fk FOREIGN KEY (id) REFERENCES job (id)
);